name: Run tests

on:
  push:
    branches:
      - master
    paths:
      - "yamlindexer/"
      - "**.py"
      - "tox.ini"
  pull_request:
    paths:
      - "yamlindexer/"
      - "**.py"
      - "tox.ini"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Generate a common hashseed for all tests
  generate-hashseed:
    runs-on: ubuntu-latest

    outputs:
      hashseed: ${{ steps.generate.outputs.hashseed }}

    steps:
      - name: Generate Hashseed
        id: generate
        run: |
          python -c "from random import randint;
          hashseed = randint(0, 4294967295)
          print(f'{hashseed=}')
          print(f'::set-output name=hashseed::{hashseed}')"

  # Tests job
  tests:
    runs-on: ubuntu-latest

    needs: generate-hashseed

    strategy:
      matrix:
        # Match versions specified in tox.ini
        python-version: ['3.6', '3.7', '3.8', 'pypy-3.8', '3.9', '3.10']

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tox with tox-gh-actions
      uses: ymyzk/run-tox-gh-actions@main
      with:
        tox-args: -vv --hashseed=${{ needs.generate-hashseed.outputs.hashseed }}